# Generated by Django 3.1.4 on 2020-12-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.TextField()),
                ('region', models.TextField()),
                ('country', models.CharField(max_length=200)),
                ('item_type', models.CharField(max_length=200)),
                ('sales_channel', models.CharField(max_length=200)),
                ('order_priority', models.CharField(max_length=1)),
                ('order_date', models.DateField()),
                ('order_id', models.BigIntegerField()),
                ('ship_date', models.DateField()),
                ('units_sold', models.BigIntegerField()),
                ('unit_price', models.BigIntegerField()),
                ('unit_cost', models.BigIntegerField()),
                ('total_revenue', models.BigIntegerField()),
                ('total_cost', models.BigIntegerField()),
                ('total_profit', models.BigIntegerField()),
            ],
        ),
    ]
