# Generated by Django 3.1.4 on 2020-12-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='total_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='total_profit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='total_revenue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='unit_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='unit_price',
            field=models.FloatField(),
        ),
    ]
